name: E2E

on: push

jobs:
  test_e2e:
    name: E2E Test
    if: ${{ !startsWith(github.ref, 'refs/heads/ci-release-v') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 20
      - name: Install
        run: yarn
      - name: Prepare
        run: |
          yarn test:e2e:setup
          yarn build
          yarn start &
          while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:9999/)" != "200" ]]; do sleep 5; done
      - name: Test
        run: yarn test:e2e
